name: usher
channels:
  - defaults                                                                                                                                                                                                    
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - cmake=3.19.6
  - protobuf=3.12.3                                                                                                                                                                                               
  - make
  - autoconf
  - boost-cpp
  - mafft
  - python
  - git
  - wget
  - rsync
  - openmpi
  - openssh
  - isa-l
